config/routes.rb
Rails.application.routes.draw do
  get 'answers/new'

  get 'sessions/new'
  post 'sessions/login_attempt'

  resources :users
  resources :questions do
    resources :answers
  end
  resources :sessions
  root to: "questions#index"
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question

  has_many  :comments, as: :commentable, dependent: :destroy
  has_many :votes, as: :voteable, dependent: :destroy 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ApplicationRecord
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :author, class_name: "User"
  has_many :comments, as: :commentable, dependent: :destroy
  has_many :answers, dependent: :destroy 
  has_many :votes, as: :voteable, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, foreign_key: :author_id
  has_many :answers
  has_many :comments, foreign_key: :commenter_id
  has_many :votes, foreign_key: :voter_id
  attr_accessor :password
  EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :username, :presence => true, :uniqueness => true, :length => {:in=>3..20}
  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password, :confirmation => true
  validates_length_of :password, :in => 6..20, :on => :create
  before_save :encrypt_password
  after_save :clear_password

  def encrypt_password
    if password.present?
      self.salt = BCrypt::Engine.generate_salt
      self.encrypted_password = BCrypt::Engine.hash_secret(password, salt)
    end
  end
  def clear_password
    self.password = nil
  end
  def self.authenticate(email="", login_password="")
      EMAIL_REGEX.match(email)
      user = User.find_by_email(email)
    if user && user.match_password(login_password)
      return user
    else
      return false
    end
  end

  def match_password(login_password="")
    encrypted_password == BCrypt::Engine.hash_secret(login_password, salt)
  end
end

app/models/vote.rb
class Vote < ApplicationRecord
  belongs_to :voter, class_name: "User"
  belongs_to :voteable, polymorphic: true

  validates_uniqueness_of :voter, scope: [:voteable_id, :voteable_type]
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def new
    @answer =  Answer.new
  end

  def create
    @question = Question.find(params[:question_id])
    @answer = @question.answers.create(answer_params)
    @answer.user_id = current_user.id
    redirect_to question_path(@question)
  end

  def destroy
    @question = Question.find(params[:question_id])
    @answer = @question.answers.find(params[:id])
    @answer.destroy
    redirect_to question_path(@question)
  end

  private
    def answer_params
      params.require(:answer).permit(:user, :body)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_action :find_question, only: [:show, :edit, :update, :destroy]

  def index
    @questions = Question.all
  end

  def show
    @answers = @question.answers.all
  end

  def new
    @question =Question.new
  end

  def edit
  end

  def create
    @question =  Question.new(question_params)
    @question.author_id = current_user.id
    if @question.save
      redirect_to @question
    else
      render 'new'
    end
  end

  def update
    if @question.update(question_params)
      redirect_to @question
    else
      render 'edit'
    end
  end

  def destroy
    @question.destroy

    redirect_to questions_path
  end

  private
  def question_params
    params.require(:question).permit(:title, :body)
  end


  def find_question
    @question = Question.find(params[:id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def login_attempt
    authorized_user = User.authenticate(params[:email],params[:login_password])
    if authorized_user
      session[:user_id] = authorized_user.id
      flash[:notice] = "Wow Welcome again, #{authorized_user.username}"
      redirect_to questions_path
    else
      flash[:danger] = 'Invalid email/password combination'
      render "new"
    end
  end

  def destroy
    log_out
    redirect_to(:action => 'questions')
  end


end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user =User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:notice]= "Success!"
      flash[:color]="valid"
      redirect_to root_url
    else
      flash[:notice]= "Form is invalid"
      flash[:color]="invalid"
      render "new"
    end
  end

private

  def user_params
     params.require(:user).permit(:username, :email, :password, :salt, :encrypted_password)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
  def logged_in?
    !current_user.nil?
  end

  def log_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
module UsersHelper

end

app/views/answers/_form.html.erb
<%= form_for ([@question, @question.answers.build ]) do |f| %>

  <p> Text:</br> <%= f.text_field :body%> </p>

  <%= f.submit :Submit %>
<% end %>
<%if @question.errors.any? %>
  <ul class="Signup_Errors">
    <% for message_error in @question.errors.full_messages %>
      <li> * <%=  message_error %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Stack</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <p> Title:</br> <%= f.text_field :title%> </p>
  <p> Text:</br> <%= f.text_field :body%> </p>

  <%= f.submit :Submit %>
<% end %>
<%if @question.errors.any? %>
  <ul class="Signup_Errors">
    <% for message_error in @question.errors.full_messages %>
      <li> * <%=  message_error %></li>
    <% end %>
  </ul>
<% end %>

app/views/questions/edit.html.erb
<h1>Edit new question</h1>
<%= render 'form' %>
<%= link_to 'Back', question_path %>

app/views/questions/index.html.erb
<h1> All Questions </h1>
<%= link_to 'New question', new_question_path %>
<table>
    <% @questions.each do |question| %>
      <tr>
        <td><%= question.title %></td>
        <td><%= question.author.username %></td>
        <td><%= link_to 'Show', question_path(question) %></td>
        <td><%= link_to 'Edit', edit_question_path(question) %></td>
        <td><%= link_to 'Destroy', question_path(question),
          method: :delete,
          data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <%end%>
</table>

app/views/questions/new.html.erb
<h1>Create new question</h1>
<%= render 'form' %>
<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p>
<strong>Title</strong>
<%= @question.title %>
</p>

<p>
<strong>Text</strong>
<%= @question.body %>
</p>

<p>
<strong>Author</strong>
<%= @question.author.username %>
</p>

<p><%= link_to 'Back',  questions_path %>

  <h2>Answers:</h2>
  <%= @answers.each do |answer| %>
    <strong> User </strong>
    <%=  answer.user.username %>
    <strong> Answer </strong>
    <%= answer.body %>
  <% end %>


  <h2>Create new answer</h2>
  <%= render 'answers/form' %>

app/views/users/new.html.erb
<h1>Sign up</h1>
<%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
  <p> Username:</br> <%= f.text_field :username, class: 'form-control'%> </p>
  <p> Email:</br> <%= f.text_field :email, class: 'form-control'%> </p>
  <p> Password:</br> <%= f.password_field :password, class: 'form-control'%> </p>
  <p> Password Confirmation:</br> <%= f.password_field :password_confirmation, class: 'form-control'%> </p>
  <%= f.submit :Signup, class: "btn btn-primary"%>
<% end %>
<%if @user.errors.any? %>
  <ul class="Signup_Errors">
    <% for message_error in @user.errors.full_messages %>
      <li> * <%=  message_error %></li>
    <% end %>
  </ul>
<% end %>